image: maven:latest

stages:
    - cache
    - test
    - build
    - deploy
# - web-deploy


variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    SPRING_PROFILES_ACTIVE: gitlab-ci
    OUTPUT_JAR_PROD: "cyio-backend-prod"
    OUTPUT_JAR_DEV: "cyio-backend-dev"

cache:
  paths:
    - .m2/repository/
    - target/

# deploy-frontend-site:
#   stage: web-deploy
#   script:
#     - rm -rf /var/www/html/
#     - pwd
#     - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
# #    - cp -rf frontend/ /var/www/html/

Build Maven Backend:
  stage: build
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

Test Springboot:
  stage: test
  allow_failure: true
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test

Deploy to Prod Environment:
  stage: deploy
  retry: 2
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
  script:
    - echo "Deploying Production Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_PROD clean package
    - ls target/
    - systemctl stop cyio-prod
    - cp target/$OUTPUT_JAR_PROD.jar /home/server-files/prod/
    - systemctl stop cyio-prod
    - systemctl enable cyio-prod

  artifacts:
    paths:
      - target/$OUTPUT_JAR_PROD.jar
  only:
    - master

Deploy to Dev Environment:
  stage: deploy
  when: manual
  retry: 2
  script:
    - echo "Deploying Development Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_DEV clean package
    - ls target/
    - systemctl stop cyio-dev
    - cp target/$OUTPUT_JAR_DEV.jar /home/server-files/dev/
    - systemctl stop cyio-dev
    - systemctl enable cyio-dev
  environment:
    name: review/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
        - target/$OUTPUT_JAR_DEV.jar
  only:
    - branches
  except:
    - master