image: maven:latest

stages:
    - cache
    # - web-deploy
    - build
    - test

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

# deploy-frontend-site:
#   stage: web-deploy
#   script:
#     - rm -rf /var/www/html/
#     - pwd
#     - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
# #    - cp -rf frontend/ /var/www/html/

build-maven-project:
  stage: build
  script:
    # - mvn $MAVEN_CLI_OPTS compile
    - cd backend
    - mvn --batch-mode --show-version compile

test-springboot:
  stage: test
  script:
    # - mvn $MAVEN_CLI_OPTS test
    - mvn --batch-mode --show-version test

# deploy_server_backend:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - master

# deploy_staging:
#   stage: deploy
#   environment:
#     name: review/$CI_COMMIT_REF_SLUG
#     url: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
#   script:
#     - echo "Deploying to staging server"
#     - web_deploy_script
#     - echo $CI_ENVIRONMENT_URL > environment_url.txt
#   artifacts:
#     paths:
#       - environment_url.txt
#   only:
#     - master

# browser_performance:
#   stage: browser_performance
#   image: docker:git
#   variables:
# #    URL: http://cyio.mlu.li/
#     URL: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
#   services:
#     - docker:stable-dind
#   script:
#     - mkdir gitlab-exporter
#     - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
#     - mkdir sitespeed-results
#     - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
#     - mv sitespeed-results/data/performance.json performance.json
#   artifacts:
#     paths:
#       - sitespeed-results/
#     reports:
#       performance: performance.json