image: maven:latest

stages:
    - cache
    - test
    - build
    - deploy
# - web-deploy


variables:
    MAVEN_CLI_OPTS: "--batch-mode --show-version"
    SPRING_PROFILES_ACTIVE: gitlab-ci
    OUTPUT_JAR_PROD: "backend-prod"
    OUTPUT_JAR_DEV: "backend-dev-build"

cache:
  paths:
    - .m2/repository/
    - target/

# deploy-frontend-site:
#   stage: web-deploy
#   script:
#     - rm -rf /var/www/html/
#     - pwd
#     - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
# #    - cp -rf frontend/ /var/www/html/

build-maven-project:
  stage: build
  parallel: 3
  retry: 2
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

test-springboot:
  stage: test
  parallel: 3
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS test

# deploy_server_backend:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - master

deploy_prod:
  stage: deploy
  when: manual
  retry: 2
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
    # url: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
  script:
    - echo "Deploying to prod server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_PROD clean package
    - ls target/
    - echo ${project.version}
    # - mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q
    # - systemctl start Cyio-SB
    # - systemctl enable Cyio-SB

  artifacts:
    paths:
      - target/backend-$VERSION.jar
  only:
    - master

deploy_review:
  stage: deploy
  retry: 2
  script:
    - echo "Deploy development backend"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_DEV clean package
    - ls /target
    - echo ${project.version}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    # url: https://$CI_ENVIRONMENT_SLUG.example.com
  artifacts:
    paths:
        - target/*.jar
  only:
    - branches
  except:
    - master


# browser_performance:
#   stage: browser_performance
#   image: docker:git
#   variables:
# #    URL: http://cyio.mlu.li/
#     URL: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
#   services:
#     - docker:stable-dind
#   script:
#     - mkdir gitlab-exporter
#     - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
#     - mkdir sitespeed-results
#     - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
#     - mv sitespeed-results/data/performance.json performance.json
#   artifacts:
#     paths:
#       - sitespeed-results/
#     reports:
#       performance: performance.json