image: maven:latest

stages:
    - cache
    - test
    - build
    - deploy
    - web-deploy
# - android-test
# - android-build


variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    SPRING_PROFILES_ACTIVE: gitlab-ci
    OUTPUT_JAR_PROD: "cyio-backend-prod"
    OUTPUT_JAR_DEV: "cyio-backend-dev"

cache:
  paths:
    - .m2/repository/
    - backend/target/

# Deploy Site to Production Environment:
Deploy React Prod Site:
  stage: web-deploy
  allow_failure: true
  script:
    # - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
    - cd react-frontend/
    - npm run build
    - mv -f build/* /var/www/prod-site/
  artifacts:
    paths:
      - react-frontend/build/
  only:
    - master

# Deploy Site to Development Environment:
Deploy React Dev Site:
  stage: web-deploy
  when: manual
  script:
    # - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
    - cd react-frontend/
    - npm run build
    - mv -f build/* /var/www/dev-site/
  artifacts:
    paths:
      - react-frontend/build/
  only:
    - branches
  except:
    - master

# Build Springboot Backend
Build Maven Backend:
  stage: build
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

# Test Springboot Backend For Production Environment
Test Springboot:
  stage: test
  allow_failure: false
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  only:
    - master

# Test Springboot Backend For Development Environment
Test Springboot:
  stage: test
  allow_failure: true
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  only:
    - branches
  except:
    - master

# Deploy Springboot Backend to Production Environment
Deploy Springboot to Prod Environment:
  stage: deploy
  allow_failure: true
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
  script:
    - echo "Deploying Production Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean package
    - sudo systemctl stop cyio-prod
    - sudo mv target/*.jar /home/server-files/prod/$OUTPUT_JAR_PROD.jar
    - sudo systemctl start cyio-prod

  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - master

# Deploy Springboot Backend to Development Environment
Deploy SpringBoot to Dev Environment:
  stage: deploy
  when: manual
  script:
    - echo "Deploying Development Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_DEV clean package
    - sudo systemctl stop cyio-dev
    - sudo mv target/*.jar /home/server-files/dev/$OUTPUT_JAR_DEV.jar
    - sudo systemctl start cyio-dev
  environment:
    name: review/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - branches
  except:
    - master