image: maven:latest

stages:
    - cache
    - test
    - build
    - deploy
# - web-deploy
# - android-test
# - android-build


variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    SPRING_PROFILES_ACTIVE: gitlab-ci
    OUTPUT_JAR_PROD: "cyio-backend-prod"
    OUTPUT_JAR_DEV: "cyio-backend-dev"

cache:
  paths:
    - .m2/repository/
    - target/

# Deploy Site to Prod Environment:
#   stage: web-deploy
#   script:
#     - rm -rf /var/www/html/
#     - pwd
#     - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
# #    - cp -rf frontend/ /var/www/html/

# Deploy Site to Dev Environment:
#   stage: web-deploy
#   script:
#     - rm -rf /var/www/html/
#     - pwd
#     - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
# #    - cp -rf frontend/ /var/www/html/

Build Maven Backend:
  stage: build
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

Test Springboot:
  stage: test
  allow_failure: true
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test

Deploy to Prod Environment:
  stage: deploy
  retry: 2
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
  script:
    - echo "Deploying Production Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean package
    - sudo systemctl stop cyio-prod
    - sudo mv target/*.jar /home/server-files/prod/$OUTPUT_JAR_PROD.jar
    - sudo systemctl start cyio-prod

  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - master

Deploy to Dev Environment:
  stage: deploy
  when: manual
  retry: 2
  script:
    - echo "Deploying Development Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_DEV clean package
    - sudo systemctl stop cyio-dev
    - sudo mv target/*.jar /home/server-files/dev/$OUTPUT_JAR_DEV.jar
    - sudo systemctl start cyio-dev
  environment:
    name: review/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - branches
  except:
    - master