image: maven:latest

stages:
#    - cache
    - test-spring
    - test-android
    - test-site
    - build-spring
    - deploy-spring
    - deploy-site


variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    SPRING_PROFILES_ACTIVE: gitlab-ci
    OUTPUT_JAR_PROD: "cyio-backend-prod"
    OUTPUT_JAR_DEV: "cyio-backend-dev"
    NPM_PATH: "/usr/local/bin/npm"

cache:
  paths:
    - backend/target/
    - react/build/

# Change Gitlab-Runner Home directory file permissions and remove node_modlues if there
default:
  before_script:
    - sudo chmod 777 /home/gitlab-runner/ -R
    - sudo rm /home/gitlab-runner/builds/SDjQd5kx/0/cs309/fall2019/nv_4/react/node_modules/ -rf
  after_script:
    - sudo chmod 777 /home/gitlab-runner/ -R
    - sudo rm /home/gitlab-runner/builds/SDjQd5kx/0/cs309/fall2019/nv_4/react/node_modules/ -rf
  

# Build Springboot Backend
Build Maven Backend:
  stage: build-spring
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

# Test Springboot Backend For Production Environment
Test Springboot Prod:
  stage: test-spring
  allow_failure: false
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  only:
    - master

# Test Springboot Backend For Development Environment
Test Springboot Dev:
  stage: test-android
  allow_failure: true
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  only:
    - branches
  except:
    - master

# Test Website Frontend For Development Environment
Test Site Dev:
  stage: test-site
  allow_failure: true
  script:
    - cd react
    - $NPM_PATH install
    # - sudo chmod -R +xwr .
    - $NPM_PATH test
  only:
    - branches
  except:
    - master

# Test Website Frontend For Production Environment
Test Site Prod:
  stage: test-site
  allow_failure: false
  script:
    - cd react
    - $NPM_PATH install
    # - sudo chmod -R +xwr .
    - $NPM_PATH test
  only:
    - master

# Test Android Application for Development Environment
Test Android Dev:
    stage: test-android
    allow_failure: true
    script:
      - cd Android/PlaceHolder
      - sudo chmod -R +xwr .
      - ./gradlew test --stacktrace
#      - sudo ./gradlew -Pci --console=plane :app:testDebug
    only:
      - branches
    except:
      - master

# Test Android Application for Production Environment
Test Android Prod:
    stage: test-spring
    allow_failure: true
    script:
      - cd Android/PlaceHolder
      - sudo chmod -R +xwr .
      - ./gradlew test --stacktrace
#      - sudo ./gradlew -Pci --console=plane :app:testDebug
    only:
      - master

# Deploy Springboot Backend to Production Environment
Deploy Springboot to Prod Environment:
  stage: deploy-spring
  allow_failure: true
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
  script:
    - echo "Deploying Production Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean package
    - sudo systemctl stop cyio-prod
    - sudo mv `ls target/*.jar | head -n 1` /home/server-files/prod/$OUTPUT_JAR_PROD.jar
    - sudo systemctl start cyio-prod
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - master

# Deploy Springboot Backend to Development Environment
Deploy SpringBoot to Dev Environment:
  stage: deploy-spring
  when: manual
  script:
    - echo "Deploying Development Backend Server"
    - cd backend
    - mvn $MAVEN_CLI_OPTS -Djar.finalName=$OUTPUT_JAR_DEV clean package
    - sudo systemctl stop cyio-dev
    - sudo mv `ls target/*.jar | head -n 1` /home/server-files/dev/$OUTPUT_JAR_DEV.jar
    - sudo systemctl start cyio-dev
  environment:
    name: review/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - branches
  except:
    - master

# Deploy Site to Production Environment:
Deploy React Prod Site:
  stage: deploy-site
  allow_failure: true
  script:
    # - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
    - cd react/
    - $NPM_PATH install
    # - sudo chmod -R +xwr .
    - CI=false $NPM_PATH run build-auto
    - sudo rm -rf /var/www/prod-site/*
    - sudo mv -f build/* /var/www/prod-site/
  artifacts:
    paths:
      - react/build/
  only:
    - master

# Deploy Site to Development Environment:
Deploy React Dev Site:
  stage: deploy-site
  when: manual
  script:
    # - sudo docker cp gitlab-runner:/builds/cs309/fall2019/nv_4/frontend/ /var/www/html/
    - cd react/
    - $NPM_PATH install
    # - sudo chmod -R +xwr .
    - CI=false $NPM_PATH run build-auto
    - sudo rm -rf /var/www/dev-site/*
    - sudo mv -f build/* /var/www/dev-site/
  artifacts:
    paths:
      - react/build/
  only:
    - branches
  except:
    - master