package com.cyio.backend;

import javax.persistence.*;
import java.util.UUID;

@Entity

@Table(name = "Games")

public class Game{

    private int id;
	private String title;
    private String blurb;
    private String about;
    @Id //set gameId as the primary key
    @GeneratedValue(strategy = GenerationType.AUTO) //This line tells Spring that the gameId will be auto generated by the database
    private final UUID gameID;
    private final UUID creatorID;
    private UUID thumbnailID;

    public Game(String title, UUID gameID, UUID creatorID) {
        this.title = title;
        this.blurb = "This is a test game";
        this.about = "Wow! This is a long description";
        this.gameID = gameID;
        this.creatorID = UUID.randomUUID();
        this.thumbnailID = UUID.randomUUID();
    }

    public UUID getGameID() {
        return gameID;
    }

    /*
    public LinkedHashMap<String, Object> getDataMap() {
        LinkedHashMap<String, Object> map = new LinkedHashMap<>();
        map.put("title", title);
        map.put("blurb", getBlurb());
        map.put("about", getAbout());
        map.put("gameId", getGameId());
        map.put("creatorId", getCreatorId());
        map.put("thumbnailId", getThumbnailId());
        return map;
    }
    */

    public String getTitle() {
        return title;
    }

    public String getBlurb() {
        return blurb;
    }

    public String getAbout() {
        return about;
    }

    public UUID getCreatorID() {
        return creatorID;
    }

    public UUID getThumbnailID() {
        return thumbnailID;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setBlurb(String blurb) {
        this.blurb = blurb;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public void setThumbnailID(UUID thumbnailID) {
        this.thumbnailID = thumbnailID;
    }
}
