package com.cyio.backend.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.persistence.*;
import javax.persistence.Entity;
import java.util.ArrayList;
import java.util.UUID;

@Entity
@Table(name = "Games")
@Component
public class Game{

    @GeneratedValue(strategy = GenerationType.AUTO) //This line tells Spring that the gameId will be auto generated by the database
    private int id;
	private String title;
    private String blurb;
    private String about;
    @Id //set gameId as the primary key
    private String gameID;
    private String creatorID;
    private String thumbnailID;
    private ArrayList<GameServer> gameServers;

    public Game(String title, String gameID, String creatorID) {
        this.title = title;
        this.blurb = "This is a test game";
        this.about = "Wow! This is a long description";
        this.gameID = gameID;
        this.creatorID = creatorID;
        this.thumbnailID ="thumbnail.jpg";
        gameServers = new ArrayList<>();
    }

    @Autowired
    public Game(){
        this("Autowire", UUID.randomUUID().toString(), UUID.randomUUID().toString());
    }

    public String getGameID() {
        return gameID;
    }

    /*
    public LinkedHashMap<String, Object> getDataMap() {
        LinkedHashMap<String, Object> map = new LinkedHashMap<>();
        map.put("title", title);
        map.put("blurb", getBlurb());
        map.put("about", getAbout());
        map.put("gameId", getGameId());
        map.put("creatorId", getCreatorId());
        map.put("thumbnailId", getThumbnailId());
        return map;
    }
    */

    public String getTitle() {
        return title;
    }

    public String getBlurb() {
        return blurb;
    }

    public String getAbout() {
        return about;
    }

    public String getCreatorID() {
        return creatorID;
    }

    public String getThumbnailID() {
        return thumbnailID;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setBlurb(String blurb) {
        this.blurb = blurb;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public void setThumbnailID(String thumbnailID) {
        this.thumbnailID = thumbnailID;
    }
}
